# deinを使うなら必須
[[plugins]]
repo = 'Shougo/dein.vim'

# vim内の非同期処理を可能に
[[plugins]]
repo = 'Shougo/vimproc.vim'

# color scheme
[[plugins]]
repo = 'tomasr/molokai'

# htmlのタグを閉じる
[[plugins]]
repo = 'alvan/vim-closetag'

# 閉じ括弧を補完
[[plugins]]
repo = 'cohama/lexima.vim'

# 文末にホワイトスペースがあれば表示
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

# vimのしたのコマンドラインをかっこよく
[[plugins]]
repo = 'itchyny/lightline.vim'

# 文法エラーチェック
#[[plugins]]
#repo = 'w0rp/ale'
#hook_source= '''
#    let g:ale_linters = {
#        \ 'python': ['flake8'],
#        \ }
#    let g:ale_fixers = {
#        \ 'python': ['autopep8', 'black', 'isort'],
#        \ }
#    let g:ale_fix_on_save = 1
#    let g:ale_lint_on_text_changed = 0
#'''

# language server protcol関連
[[plugins]]
repo = 'prabirshrestha/async.vim'

# language server protcol関連
[[plugins]]
repo = 'prabirshrestha/vim-lsp'
hook_add='''
    if executable('pyls')
        au User lsp_setup call lsp#register_server({
            \ 'name': 'pyls',
            \ 'cmd': {server_info->['pyls']},
            \ 'whitelist': ['python'],
            \ })
    endif
'''

# language server protcol関連
[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'

# language server protcol関連
[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'
